# Use uma imagem oficial do Node.js
FROM node:18-alpine

# Diretório de trabalho dentro do container
WORKDIR /app

# Copia package.json e package-lock.json (se existir)
COPY package*.json ./

# Instala as dependências (somente produção)
RUN npm install --production

# Copia todo o código para dentro do container
COPY . .

# Exponha a porta que o app usará
EXPOSE 4000

# Comando para rodar a API
CMD ["nodemon", "./src/server.js"]
